************************************************************************
*!*	Code in cims!fund design for gen report
*!*	Field report_support

*!*		A = Indv. HS					H = Indv. PA & Group PA
*!*		B = Group HS					I  = Indv. HS & Group HS & Indv. PA	
*!*		C = Indv. PA					J  = Indv. HS & Group HS & Indv. PA & Group PA
*!*		D = Group PA					K  = 
*!*		E = Indv. HS & Indv.PA			L  = 
*!*		F = Group HS & Group PA		N  = 
*!*		G = Indv. HS & Group HS		O  =
************************************************************************
	