* Treeview.h

* Treeline constants
#DEFINE tvwTreeLines 0
#DEFINE tvwRootLines 1 

* Relationship constants

#DEFINE tvwFirst    0
#DEFINE tvwLast     1
#DEFINE tvwNext     2
#DEFINE tvwPrevious 3
#DEFINE tvwChild    4

* TreeStyle Constants

#DEFINE tvwTextOnly                      0
#DEFINE tvwPictureText                   1
#DEFINE tvwPlusMinusText                 2
#DEFINE tvwPlusPictureText               3
#DEFINE tvwTreelinesText                 4
#DEFINE tvwTreelinesPictureText          5
#DEFINE tvwTreelinesPlusMinusText        6
#DEFINE tvwTreelinesPlusMinusPictureText 7

* LabelEdit Constants

#DEFINE tvwAutomatic 0
#DEFINE tvwManual    1 

